version: '3.8'
services:
  api:
    depends_on:
      - db
    build: .
    ports:
      - 8081:8081
    restart: always
    environment:
      SECRET_KEY: lol
      DSN: postgresql://myuser:mypassword@db/forum
    networks:
      - db-network

  db:
    build:
      context: forum/db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: forum
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-network

networks:
  db-network:


volumes:
  db-data:
