version: '3.8'
services:
  api:
    depends_on:
      - db
    build: .
    ports:
      - 8081:8081
    restart: always
    environment:
      SECRET_KEY: lol
      DSN: postgresql://myuser:mypassword@db:5432/forum
      MIN_CONNECTION_COUNT: 5
      MAX_CONNECTION_COUNT: 10
    networks:
      - db-network
      - monitoring
    command: sh -c 'alembic upgrade head && python -m forum'

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: forum
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-network
    ports:
      - 5432:5432
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:9.2.15
    container_name: grafana
    networks:
      - monitoring
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - prometheus

networks:
  db-network:
  monitoring:

volumes:
  db-data:
