version: '3'
services:
  api:
    depends_on:
      - db
    build: .
    ports:
      - 8081:8081
    restart: always
    environment:
      SECRET_KEY: lol
      DSN: postgresql://myuser:mypassword@db/forum
  
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: forum
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: