"""initial_migration

Revision ID: 826c064620dd
Revises: 
Create Date: 2023-04-23 10:45:33.254694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "826c064620dd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("about", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("email", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("hashed_password", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_login_at", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("user_id", name="users_pkey"),
    )

    op.create_table(
        "friends",
        sa.Column("from_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("to_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("accepted_at", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["from_id"],
            ["users.user_id"],
            name="friends_from_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_id"], ["users.user_id"], name="friends_to_id_fkey", ondelete="CASCADE"
        ),
        sa.UniqueConstraint("from_id", "to_id", name="friends_from_id_to_id_key"),
    )

    op.create_index("idx_to_id", "friends", ["to_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_to_id", table_name="friends")

    op.drop_table("friends")

    op.drop_table("users")
    # ### end Alembic commands ###
