USER_NOT_FOUND = 'user not found'
ALREADY_FRIENDS = 'already friends'
SAME_FRIENDS_IDS = 'friends IDs should differ'
WRONG_ID_OR_PASSWD = 'wrong ID or password'
AUTHENTICATION_REQUIRED = 'authentication required'